# Generated by Django 3.2.8 on 2022-01-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='media/images/'),
        ),
    ]
