# Generated by Django 3.2.8 on 2022-01-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='media/images/tennisball.jpg', null=True, upload_to='media/media/images/'),
        ),
    ]
